-- Update questions with structured explanations and mark as trial-featured
-- Generated by Claude

-- Question 1: Lithium and Ibuprofen interaction
UPDATE questions SET
  is_trial_featured = TRUE,
  trial_display_order = 1,
  explanation_structured = '{
    "summary": "NSAIDs like ibuprofen reduce renal lithium clearance, causing lithium levels to rise and increasing the risk of toxicity. This pharmacokinetic interaction requires careful monitoring.",
    "key_points": [
      "NSAIDs inhibit prostaglandin synthesis, reducing renal blood flow and lithium excretion",
      "Lithium has a narrow therapeutic index (0.4-1.0 mmol/L), making even small increases dangerous",
      "Symptoms of lithium toxicity include tremor, confusion, seizures, and cardiac arrhythmias",
      "If NSAIDs are necessary, monitor lithium levels more frequently and consider dose reduction"
    ],
    "clinical_pearl": "If a patient on lithium needs pain relief, paracetamol is the safest first-line choice. If an NSAID is essential, use the lowest dose for the shortest duration and check lithium levels within 5-7 days.",
    "why_wrong": {
      "B": "Atorvastatin does not significantly interact with lithium. Statins are metabolized hepatically and do not affect renal lithium clearance.",
      "C": "Loratadine is a non-sedating antihistamine with no significant effect on lithium levels or renal function.",
      "D": "Omeprazole, a proton pump inhibitor, does not interact with lithium metabolism or excretion.",
      "E": "Levothyroxine does not affect lithium levels, though lithium can affect thyroid function over time."
    },
    "exam_tip": "Remember the mnemonic \"NSAID = No Safety At Increased Doses\" for lithium patients. Always think about renal clearance when considering drug interactions with lithium.",
    "related_topics": ["drug-interactions", "lithium-monitoring", "renal-drug-clearance"]
  }'::jsonb
WHERE id = '74e8d647-6f82-4e8f-9f70-cc53eec86e5c';

-- Question 2: Primary route of drug excretion
UPDATE questions SET
  is_trial_featured = TRUE,
  trial_display_order = 2,
  explanation_structured = '{
    "summary": "The kidneys are the primary organ for drug excretion, using glomerular filtration, active tubular secretion, and passive reabsorption to eliminate drugs and metabolites from the body.",
    "key_points": [
      "Glomerular filtration removes unbound drug based on molecular size and charge",
      "Active tubular secretion uses carrier proteins to transport drugs into the tubular fluid",
      "Passive reabsorption allows lipophilic drugs to be reabsorbed back into circulation",
      "Renal impairment significantly affects drug dosing for renally-cleared medications"
    ],
    "clinical_pearl": "When counselling patients with kidney disease, always check if their medications need dose adjustment. The BNF provides specific guidance for each drug based on eGFR ranges.",
    "why_wrong": {
      "B": "Biliary excretion is important for larger molecules and those undergoing enterohepatic circulation, but it is secondary to renal excretion for most drugs.",
      "C": "Sweat is a minor excretion route with minimal clinical significance for drug elimination.",
      "D": "Breast milk excretion is clinically important for nursing mothers but represents a minor elimination pathway.",
      "E": "Saliva excretion is minimal and primarily useful for therapeutic drug monitoring rather than elimination."
    },
    "exam_tip": "For questions about drug excretion, think kidneys first! The exception is for very large molecules or highly lipophilic drugs that may favor biliary excretion.",
    "related_topics": ["renal-impairment", "pharmacokinetics", "dose-adjustment"]
  }'::jsonb
WHERE id = 'bd597b5c-30c0-401b-a769-3c16b39b5ad2';

-- Question 3: SSRI side effects - Nausea
UPDATE questions SET
  is_trial_featured = TRUE,
  trial_display_order = 3,
  explanation_structured = '{
    "summary": "Nausea is the most common side effect when starting SSRIs, caused by increased serotonin activity in the GI tract. It typically improves within 1-2 weeks of treatment.",
    "key_points": [
      "GI side effects occur because 95% of body serotonin is found in the gut",
      "Starting at a low dose and taking with food can minimize nausea",
      "Other common early SSRI side effects include headache, insomnia, and anxiety",
      "Sexual dysfunction and weight changes are longer-term side effects"
    ],
    "clinical_pearl": "When starting patients on SSRIs, warn them about initial nausea and reassure them it usually settles within 2 weeks. Suggest taking the medication with food or in the evening if it causes daytime nausea.",
    "why_wrong": {
      "A": "Bradycardia is not typically associated with SSRIs. In fact, some SSRIs can cause minor increases in heart rate.",
      "B": "Hypertension is not a common SSRI side effect. SSRIs generally have minimal cardiovascular effects.",
      "D": "Constipation is more associated with tricyclic antidepressants due to their anticholinergic effects, not SSRIs.",
      "E": "Urinary retention is an anticholinergic side effect seen with TCAs, not SSRIs."
    },
    "exam_tip": "SSRIs have a predictable side effect profile: GI effects early (nausea, diarrhea), then sexual dysfunction and potential weight gain with longer use. TCAs cause anticholinergic effects (dry mouth, constipation, urinary retention).",
    "related_topics": ["antidepressant-side-effects", "patient-counselling", "ssri-pharmacology"]
  }'::jsonb
WHERE id = '38957ce8-b922-4046-b877-80ccbbcf926d';

-- Question 4: Therapeutic Index
UPDATE questions SET
  is_trial_featured = TRUE,
  trial_display_order = 4,
  explanation_structured = '{
    "summary": "The therapeutic index (TI) measures drug safety by comparing the toxic dose to the therapeutic dose. A high TI means a wide safety margin; a low TI requires careful dosing and monitoring.",
    "key_points": [
      "TI = TD50/ED50 (toxic dose for 50% / effective dose for 50%)",
      "Drugs with low TI include warfarin, digoxin, lithium, aminoglycosides, and phenytoin",
      "Low TI drugs often require therapeutic drug monitoring (TDM)",
      "A high TI indicates the drug can be given over a wide dose range safely"
    ],
    "clinical_pearl": "Remember ''DLWAP'' for narrow therapeutic index drugs: Digoxin, Lithium, Warfarin, Aminoglycosides, Phenytoin. These all require monitoring and careful dose adjustment.",
    "why_wrong": {
      "A": "Bioavailability refers to the fraction of drug reaching systemic circulation, not the safety margin between doses.",
      "B": "Absorption rate describes how quickly a drug enters the bloodstream, which is a separate pharmacokinetic parameter.",
      "D": "Metabolism rate is described by parameters like half-life and clearance, not therapeutic index.",
      "E": "Elimination half-life describes how long it takes for drug concentration to halve, not the safety margin."
    },
    "exam_tip": "When you see ''therapeutic index'' in a question, think SAFETY MARGIN. Low TI = more dangerous = needs monitoring. High TI = safer = wider dosing flexibility.",
    "related_topics": ["therapeutic-drug-monitoring", "drug-safety", "pharmacokinetics"]
  }'::jsonb
WHERE id = '494d9cbe-43ff-497f-a81c-b992b0acfbeb';

-- Question 5: Warfarin and Erythromycin interaction
UPDATE questions SET
  is_trial_featured = TRUE,
  trial_display_order = 5,
  explanation_structured = '{
    "summary": "Erythromycin inhibits CYP3A4 and CYP1A2 enzymes that metabolize warfarin, leading to increased warfarin levels, elevated INR, and higher bleeding risk requiring more frequent monitoring.",
    "key_points": [
      "Warfarin is metabolized by multiple CYP450 enzymes (CYP2C9, CYP3A4, CYP1A2)",
      "Erythromycin is a potent CYP3A4 inhibitor affecting warfarin metabolism",
      "INR should be checked 3-5 days after starting erythromycin",
      "Other macrolides like clarithromycin have similar interactions; azithromycin has less effect"
    ],
    "clinical_pearl": "When a patient on warfarin needs an antibiotic, azithromycin is often the safest macrolide choice as it has minimal CYP450 interaction. Always check INR more frequently when adding any new medication.",
    "why_wrong": {
      "A": "Amoxicillin has minimal effect on warfarin metabolism. It may rarely affect INR by altering gut flora and vitamin K production, but this is less predictable than enzyme inhibition.",
      "C": "Atenolol does not interact with warfarin metabolism and is safe to co-prescribe.",
      "D": "Cetirizine is a non-sedating antihistamine with no significant CYP450 interactions affecting warfarin.",
      "E": "Metformin does not affect warfarin metabolism or INR values."
    },
    "exam_tip": "For warfarin interactions, remember enzyme INHIBITORS increase INR (bleeding risk) and enzyme INDUCERS decrease INR (clotting risk). Erythromycin and clarithromycin are inhibitors; rifampicin is an inducer.",
    "related_topics": ["cyp450-interactions", "anticoagulant-monitoring", "macrolide-antibiotics"]
  }'::jsonb
WHERE id = '51beaa89-8a8e-4ddb-a874-77ec492c9a8d';

-- Question 6: Rifampicin and Phenytoin interaction
UPDATE questions SET
  is_trial_featured = TRUE,
  trial_display_order = 6,
  explanation_structured = '{
    "summary": "Rifampicin is one of the most potent CYP450 enzyme inducers, significantly increasing phenytoin metabolism and reducing its serum levels, which can lead to breakthrough seizures.",
    "key_points": [
      "Rifampicin induces CYP2C9, CYP2C19, and CYP3A4 which metabolize phenytoin",
      "Enzyme induction takes 1-2 weeks to develop fully and persists for 2-3 weeks after stopping",
      "Phenytoin levels may need to be increased by 50-100% during rifampicin therapy",
      "Similar interactions occur with carbamazepine, lamotrigine, and many other drugs"
    ],
    "clinical_pearl": "Rifampicin affects almost every drug metabolized by CYP450 enzymes. When prescribing rifampicin, always review ALL medications and warn patients about potential contraceptive failure.",
    "why_wrong": {
      "B": "Omeprazole is a weak CYP2C19 inhibitor, which would increase rather than decrease phenytoin levels.",
      "C": "Simvastatin is metabolized by CYP3A4 but does not significantly affect phenytoin metabolism.",
      "D": "Amoxicillin has no significant effect on CYP450 enzymes or phenytoin levels.",
      "E": "Loratadine does not affect hepatic enzyme activity or phenytoin metabolism."
    },
    "exam_tip": "Rifampicin is the ''universal inducer'' - it speeds up metabolism of almost everything! Questions about enzyme inducers often feature rifampicin, carbamazepine, phenytoin, or St Johns Wort.",
    "related_topics": ["enzyme-induction", "antiepileptic-drugs", "tuberculosis-treatment"]
  }'::jsonb
WHERE id = '5989ce96-e443-4a9e-aada-7ef96233775e';

-- Question 7: Bupropion for sexual dysfunction
UPDATE questions SET
  is_trial_featured = TRUE,
  trial_display_order = 7,
  explanation_structured = '{
    "summary": "Bupropion is an atypical antidepressant that works via norepinephrine and dopamine reuptake inhibition, with minimal serotonergic activity, making it the best choice for patients experiencing SSRI-induced sexual dysfunction.",
    "key_points": [
      "Sexual dysfunction affects 30-70% of patients on SSRIs/SNRIs",
      "Bupropion has the lowest rate of sexual side effects among antidepressants",
      "It can also help with weight management and smoking cessation",
      "Contraindicated in patients with seizure disorders or eating disorders"
    ],
    "clinical_pearl": "Bupropion is sometimes added to SSRIs specifically to counteract sexual side effects rather than switching completely. This ''antidepressant augmentation'' approach preserves the SSRI benefits while addressing the sexual dysfunction.",
    "why_wrong": {
      "A": "Amitriptyline, a tricyclic antidepressant, commonly causes sexual dysfunction due to its anticholinergic and antihistaminic effects.",
      "B": "Sertraline is an SSRI and would likely cause similar or worse sexual dysfunction as the current medication.",
      "D": "Mirtazapine can cause sexual dysfunction, though less than SSRIs. It also causes significant sedation and weight gain.",
      "E": "Duloxetine is an SNRI with similar rates of sexual dysfunction to SSRIs."
    },
    "exam_tip": "When asked about antidepressant side effects: SSRIs/SNRIs = sexual dysfunction and GI effects; TCAs = anticholinergic effects; Mirtazapine = sedation and weight gain; Bupropion = seizure risk but minimal sexual effects.",
    "related_topics": ["antidepressant-selection", "sexual-dysfunction", "depression-management"]
  }'::jsonb
WHERE id = 'fdae7747-5da7-4c7a-9558-3429dcc54312';

-- Question 8: First-line treatment for GAD
UPDATE questions SET
  is_trial_featured = TRUE,
  trial_display_order = 8,
  explanation_structured = '{
    "summary": "SSRIs like sertraline are first-line pharmacotherapy for generalized anxiety disorder due to their efficacy, safety profile, and lack of dependence potential compared to benzodiazepines.",
    "key_points": [
      "SSRIs (sertraline, escitalopram) and SNRIs (venlafaxine, duloxetine) are first-line for GAD",
      "Benzodiazepines are only for short-term use (2-4 weeks) due to dependence risk",
      "Pregabalin is an alternative if SSRIs are ineffective or not tolerated",
      "CBT (Cognitive Behavioural Therapy) should be offered alongside medication"
    ],
    "clinical_pearl": "When starting an SSRI for anxiety, warn patients that anxiety may temporarily worsen in the first 1-2 weeks before improving. Starting at half the usual dose can minimize this effect.",
    "why_wrong": {
      "A": "Lorazepam is a benzodiazepine that provides rapid relief but is not first-line due to dependence risk, tolerance development, and rebound anxiety on discontinuation.",
      "B": "Buspirone is an alternative anxiolytic but takes 2-4 weeks to work and is less effective than SSRIs for GAD.",
      "D": "Olanzapine is an antipsychotic not indicated for first-line GAD treatment and has significant metabolic side effects.",
      "E": "Valproate is a mood stabilizer used in bipolar disorder and epilepsy, not for anxiety disorders."
    },
    "exam_tip": "For anxiety disorders, think ''SSRIs first, benzos last''. Benzodiazepines are reserved for short-term crisis management or when rapid relief is essential.",
    "related_topics": ["anxiety-treatment", "ssri-prescribing", "benzodiazepine-dependence"]
  }'::jsonb
WHERE id = '1f5aad53-0fcc-4543-ace3-97ffca6653b4';

-- Question 9: Lithium monitoring
UPDATE questions SET
  is_trial_featured = TRUE,
  trial_display_order = 9,
  explanation_structured = '{
    "summary": "Lithium serum level monitoring is critical during initiation because lithium has a narrow therapeutic index (0.4-1.0 mmol/L) and toxicity can be life-threatening.",
    "key_points": [
      "Check lithium levels 5-7 days after starting or any dose change (steady state)",
      "Take blood sample 12 hours post-dose for accurate measurement",
      "Therapeutic range: 0.4-1.0 mmol/L (lower end for maintenance, higher for acute mania)",
      "Also monitor renal function, thyroid function, and calcium at baseline and every 6 months"
    ],
    "clinical_pearl": "The ''12-hour rule'' is essential: always take lithium blood samples exactly 12 hours after the last dose. Results taken at other times cannot be interpreted using standard reference ranges.",
    "why_wrong": {
      "B": "Liver function tests are not routinely required for lithium as it is renally excreted, not hepatically metabolized.",
      "C": "Serum cholesterol is not affected by lithium and is not part of routine lithium monitoring.",
      "D": "Platelet count is not affected by lithium. This monitoring is required for valproate, not lithium.",
      "E": "Eye examination is not required for lithium. This is needed for hydroxychloroquine and ethambutol."
    },
    "exam_tip": "Lithium monitoring mnemonic: ''TRACk'' - Thyroid, Renal function, (lithium) Assay/levels, Calcium. Check levels weekly during initiation, then every 3-6 months once stable.",
    "related_topics": ["lithium-therapy", "therapeutic-drug-monitoring", "bipolar-disorder"]
  }'::jsonb
WHERE id = '6c78a26d-f13f-46cd-80ce-325c3a442698';

-- Question 10: Antipsychotic switch for EPS
UPDATE questions SET
  is_trial_featured = TRUE,
  trial_display_order = 10,
  explanation_structured = '{
    "summary": "Aripiprazole is a partial dopamine agonist with the lowest risk of extrapyramidal side effects among commonly used antipsychotics, making it ideal for patients experiencing EPS.",
    "key_points": [
      "EPS includes acute dystonia, akathisia, parkinsonism, and tardive dyskinesia",
      "First-generation antipsychotics (haloperidol) have highest EPS risk",
      "Among atypicals, clozapine and quetiapine have lowest EPS risk, but other concerns limit their use",
      "Aripiprazole unique mechanism (partial D2 agonism) explains its favorable EPS profile"
    ],
    "clinical_pearl": "If a patient develops acute dystonia (muscle spasms, torticollis), treat immediately with procyclidine or benztropine IM/IV. Akathisia (restlessness) is often missed - always ask about inner restlessness.",
    "why_wrong": {
      "A": "Haloperidol is a first-generation antipsychotic with very high EPS risk - switching to this would worsen symptoms.",
      "B": "Clozapine has the lowest EPS risk but is reserved for treatment-resistant schizophrenia due to agranulocytosis risk requiring weekly blood monitoring.",
      "C": "Olanzapine has lower EPS risk than haloperidol but significant metabolic side effects (weight gain, diabetes) make it less ideal.",
      "D": "Chlorpromazine is a first-generation antipsychotic with moderate-high EPS risk and would not be appropriate."
    },
    "exam_tip": "Rank antipsychotics by EPS risk: Haloperidol > Risperidone > Olanzapine > Quetiapine > Aripiprazole > Clozapine. The ones with lowest EPS often have other issues (metabolic or monitoring requirements).",
    "related_topics": ["extrapyramidal-side-effects", "antipsychotic-selection", "schizophrenia-treatment"]
  }'::jsonb
WHERE id = 'fc9a0918-9732-47c8-b8f5-d4e41148e4e1';

-- Question 11: Live vaccine contraindication
UPDATE questions SET
  is_trial_featured = TRUE,
  trial_display_order = 11,
  explanation_structured = '{
    "summary": "Immunocompromised patients must not receive live vaccines because the attenuated organisms can cause serious vaccine-strain infections when the immune system cannot control them.",
    "key_points": [
      "Live vaccines include MMR, varicella, BCG, rotavirus, nasal flu spray, yellow fever, and oral typhoid",
      "Immunocompromised states include HIV with low CD4, chemotherapy, high-dose steroids, and biologics",
      "Inactivated vaccines are safe and often recommended for immunocompromised patients",
      "Household contacts should receive vaccines to provide indirect protection"
    ],
    "clinical_pearl": "If an immunocompromised patient needs protection, vaccinate their household contacts instead. Also ensure patients complete live vaccines before starting immunosuppressive therapy when possible.",
    "why_wrong": {
      "A": "A local reaction (redness, swelling at injection site) is not a contraindication - it is a common, expected response.",
      "C": "Minor infections like colds are not contraindications to vaccination. Only defer if the patient has a fever.",
      "D": "Family history of adverse events is not a contraindication unless the patient themselves had a severe reaction.",
      "E": "Breastfeeding is not a contraindication to live vaccines for the mother. Most vaccines are safe during breastfeeding."
    },
    "exam_tip": "Memorize the live vaccines using ''MMR + others'': MMR, Varicella, BCG, Rotavirus, Nasal flu, Yellow fever, Oral typhoid. These are all contraindicated in immunosuppression.",
    "related_topics": ["vaccination-schedule", "immunocompromised-patients", "contraindications"]
  }'::jsonb
WHERE id = '0f19bb8f-9c22-458b-82a6-0b2a62b279ae';

-- Question 12: ACE inhibitor and NSAID interaction
UPDATE questions SET
  is_trial_featured = TRUE,
  trial_display_order = 12,
  explanation_structured = '{
    "summary": "NSAIDs reduce the antihypertensive effect of ACE inhibitors by inhibiting prostaglandin synthesis, which is needed for the vasodilatory and natriuretic effects of ACE inhibitors.",
    "key_points": [
      "Prostaglandins cause vasodilation and promote sodium excretion",
      "NSAIDs block prostaglandin synthesis, causing sodium retention and vasoconstriction",
      "This pharmacodynamic interaction can raise blood pressure by 5-10 mmHg",
      "The combination also increases risk of acute kidney injury (the ''triple whammy'')"
    ],
    "clinical_pearl": "The ''triple whammy'' combination of ACE inhibitor + diuretic + NSAID significantly increases acute kidney injury risk, especially in elderly or volume-depleted patients. Avoid if possible.",
    "why_wrong": {
      "A": "Hypotension is not typically caused by adding NSAIDs - the opposite occurs due to reduced antihypertensive efficacy.",
      "C": "Hyperkalemia is a risk with ACE inhibitors alone and can be worsened by NSAIDs, but this is not the primary pharmacodynamic interaction asked about.",
      "D": "GI bleeding is a risk of NSAIDs alone, not specifically a drug interaction with ACE inhibitors.",
      "E": "Acute kidney injury is a potential consequence but relates to reduced renal perfusion, not a direct pharmacodynamic interaction on BP control."
    },
    "exam_tip": "NSAIDs antagonize three antihypertensive classes especially: ACE inhibitors, ARBs, and diuretics. All work partly through prostaglandin-mediated effects that NSAIDs block.",
    "related_topics": ["drug-interactions", "hypertension-management", "nsaid-risks"]
  }'::jsonb
WHERE id = '1e987f39-0205-4938-a16d-a43bdc998b68';

-- Question 13: Bupropion and weight
UPDATE questions SET
  is_trial_featured = TRUE,
  trial_display_order = 13,
  explanation_structured = '{
    "summary": "Bupropion is weight-neutral or may cause modest weight loss, making it the ideal antidepressant choice for patients concerned about weight gain from mirtazapine or other antidepressants.",
    "key_points": [
      "Mirtazapine causes significant weight gain due to histamine H1 receptor blockade and increased appetite",
      "Bupropion inhibits norepinephrine and dopamine reuptake with minimal effect on appetite",
      "Bupropion is approved as a component of weight loss medication (Contrave/Mysimba)",
      "SSRIs are generally weight-neutral short-term but may cause modest gain long-term"
    ],
    "clinical_pearl": "When switching from mirtazapine due to weight gain, bupropion is often the best choice. However, remember that bupropion is contraindicated in patients with eating disorders due to seizure risk.",
    "why_wrong": {
      "A": "Amitriptyline is a tricyclic antidepressant well-known for causing significant weight gain due to antihistamine and anticholinergic effects.",
      "B": "Citalopram may cause weight gain with long-term use, though less than mirtazapine.",
      "C": "Sertraline is relatively weight-neutral but not as favorable as bupropion for weight-concerned patients.",
      "D": "Paroxetine is the SSRI most associated with weight gain and would be a poor choice here."
    },
    "exam_tip": "Antidepressant weight effects: Most gain = Mirtazapine, TCAs, Paroxetine. Weight neutral = Bupropion, Sertraline, Fluoxetine. Bupropion may even help weight loss.",
    "related_topics": ["antidepressant-side-effects", "weight-management", "depression-treatment"]
  }'::jsonb
WHERE id = '11278291-80d4-4aea-8c83-5d0863a0e4cc';

-- Question 14: Colorectal cancer screening
UPDATE questions SET
  is_trial_featured = TRUE,
  trial_display_order = 14,
  explanation_structured = '{
    "summary": "Colonoscopy screening is secondary prevention because it aims to detect colorectal cancer or precancerous polyps early, before symptoms develop, when treatment is most effective.",
    "key_points": [
      "Primary prevention reduces risk of disease occurring (diet, exercise, avoiding carcinogens)",
      "Secondary prevention detects disease early through screening (colonoscopy, mammography, smears)",
      "Tertiary prevention manages existing disease to prevent complications",
      "UK bowel cancer screening offers FIT tests (ages 60-74) with colonoscopy for positive results"
    ],
    "clinical_pearl": "The UK NHS bowel cancer screening programme uses FIT (faecal immunochemical test) every 2 years for ages 60-74. Colonoscopy is offered if FIT is positive or for high-risk individuals.",
    "why_wrong": {
      "A": "Increasing dietary fiber is primary prevention - it aims to prevent cancer from developing in the first place.",
      "B": "Physical activity is primary prevention, reducing colorectal cancer risk through various mechanisms.",
      "D": "HPV vaccination is primary prevention for HPV-related cancers (cervical, some head/neck cancers), not colorectal cancer.",
      "E": "Avoiding red and processed meat is primary prevention, reducing exposure to carcinogenic compounds."
    },
    "exam_tip": "Prevention levels: Primary = stop disease occurring, Secondary = early detection, Tertiary = reduce complications. Screening tests (mammography, colonoscopy, smears) are always secondary prevention.",
    "related_topics": ["cancer-screening", "public-health", "preventive-medicine"]
  }'::jsonb
WHERE id = '0a02c7aa-5676-4fa8-85b6-6b38d758aded';

-- Question 15: Digoxin dose adjustment in renal impairment
UPDATE questions SET
  is_trial_featured = TRUE,
  trial_display_order = 15,
  explanation_structured = '{
    "summary": "Digoxin is primarily excreted unchanged by the kidneys, so patients with reduced renal function (eGFR 25 mL/min) require significant dose reduction to prevent accumulation and toxicity.",
    "key_points": [
      "70% of digoxin is excreted unchanged in urine",
      "Digoxin has a narrow therapeutic index (1.0-2.0 ng/mL for most indications)",
      "Toxicity signs include nausea, visual disturbances (yellow vision), and arrhythmias",
      "Dose reduction of 50% or more may be needed in severe renal impairment"
    ],
    "clinical_pearl": "In renal impairment, reduce digoxin dose and increase monitoring. Check digoxin levels 6 hours post-dose. Also monitor potassium - hypokalemia increases digoxin toxicity risk.",
    "why_wrong": {
      "B": "Aspirin is metabolized hepatically to salicylic acid. While high doses should be avoided in renal impairment, standard low-dose aspirin does not require adjustment.",
      "C": "Atorvastatin is hepatically metabolized and does not require dose adjustment in renal impairment.",
      "D": "Levothyroxine dosing is based on thyroid function tests, not renal function, as it is not renally cleared.",
      "E": "Loratadine is primarily hepatically metabolized and does not require significant dose adjustment in renal impairment."
    },
    "exam_tip": "Drugs needing renal dose adjustment often end in ''-mycin'' (aminoglycosides), ''-cillin'' (some penicillins), and include digoxin, lithium, metformin, and DOACs. Check BNF renal appendix!",
    "related_topics": ["renal-impairment", "dose-adjustment", "digoxin-toxicity"]
  }'::jsonb
WHERE id = '89261e5e-4f14-4aaa-b741-eddf97dbf84f';

-- Question 16: Schedule 2 controlled drugs
UPDATE questions SET
  is_trial_featured = TRUE,
  trial_display_order = 16,
  explanation_structured = '{
    "summary": "Schedule 2 controlled drugs (like morphine, oxycodone, fentanyl) require pharmacies to maintain detailed registers recording all receipts and supplies, which must be kept for 2 years.",
    "key_points": [
      "Schedule 2 includes opioids (morphine, diamorphine, fentanyl) and stimulants (amphetamines)",
      "CD register entries must be made within 24 hours and include quantity, form, and supplier/patient details",
      "Registers must be bound books with no erasures (mistakes should be crossed out and dated)",
      "Records must be kept for 2 years from the last entry date"
    ],
    "clinical_pearl": "When running balances do not match physical stock, a discrepancy must be investigated and documented. Regular stock checks (ideally daily) help identify discrepancies early.",
    "why_wrong": {
      "A": "Schedule 1 drugs (LSD, cannabis, ecstasy) have no recognized medical use in the UK and are not held in community pharmacies.",
      "C": "Schedule 3 drugs (buprenorphine, temazepam, tramadol) require safe custody but not CD register entries.",
      "D": "Schedule 4 drugs (benzodiazepines, anabolic steroids) have minimal record-keeping requirements beyond normal POM records.",
      "E": "Schedule 5 drugs (low-strength codeine preparations, some cough medicines) can be sold OTC with minimal restrictions."
    },
    "exam_tip": "CD schedules: S1 = no medical use, S2 = full controls + register, S3 = safe custody (usually) but no register, S4/S5 = minimal controls. Remember ''STOMP'' for S2: Strong opioids, True amphetamines.",
    "related_topics": ["controlled-drugs", "pharmacy-law", "record-keeping"]
  }'::jsonb
WHERE id = '06f868c9-79f5-4330-8d92-d4aaa2599d1c';

-- Question 17: First-pass metabolism - Morphine
UPDATE questions SET
  is_trial_featured = TRUE,
  trial_display_order = 17,
  explanation_structured = '{
    "summary": "Morphine undergoes extensive first-pass metabolism in the liver, reducing its oral bioavailability to approximately 30%. This is why oral morphine doses are much higher than parenteral doses.",
    "key_points": [
      "First-pass metabolism occurs as drug passes through gut wall and liver before reaching systemic circulation",
      "Morphine is converted to morphine-3-glucuronide (inactive) and morphine-6-glucuronide (active)",
      "Oral:parenteral dose ratio for morphine is approximately 3:1",
      "Other high first-pass drugs include GTN, propranolol, and verapamil"
    ],
    "clinical_pearl": "When converting morphine from IV to oral, multiply the IV dose by 3. For example, 10mg IV morphine = approximately 30mg oral morphine.",
    "why_wrong": {
      "B": "Furosemide has variable oral absorption (50-70%) but this is due to poor absorption rather than first-pass metabolism.",
      "C": "Levothyroxine has low bioavailability (40-80%) due to incomplete absorption, not first-pass metabolism.",
      "D": "Alendronate has very low bioavailability (<1%) due to poor absorption from the GI tract, not first-pass metabolism.",
      "E": "Ibuprofen is well absorbed with minimal first-pass metabolism and has approximately 80-100% bioavailability."
    },
    "exam_tip": "High first-pass metabolism drugs: GTN (why given sublingual), morphine, propranolol, lidocaine (not given orally), and some statins. These often need alternative routes or higher oral doses.",
    "related_topics": ["pharmacokinetics", "bioavailability", "opioid-dosing"]
  }'::jsonb
WHERE id = 'a93245d9-25e1-4598-9e3c-118474446572';

-- Question 18: SNRIs in CKD
UPDATE questions SET
  is_trial_featured = TRUE,
  trial_display_order = 18,
  explanation_structured = '{
    "summary": "SNRIs like venlafaxine and duloxetine require careful consideration in chronic kidney disease because they are renally cleared and their active metabolites can accumulate, potentially causing adverse effects.",
    "key_points": [
      "Venlafaxine and its active metabolite O-desmethylvenlafaxine are renally excreted",
      "Dose reduction of 25-50% is needed in moderate-severe CKD",
      "SNRIs can also increase blood pressure, which may worsen CKD progression",
      "SSRIs like sertraline or escitalopram may be safer alternatives in CKD"
    ],
    "clinical_pearl": "In CKD patients needing antidepressants, sertraline is often the safest first choice - it has minimal renal excretion and a good safety profile. Avoid duloxetine if eGFR is below 30.",
    "why_wrong": {
      "A": "SSRIs generally have good safety profiles in CKD and do not require significant dose adjustment for most agents.",
      "C": "TCAs require caution due to anticholinergic effects and cardiac risks, but renal excretion is not the primary concern.",
      "D": "MAOIs are rarely used due to dietary restrictions and drug interactions, but renal function is not the main limitation.",
      "E": "Atypical antidepressants vary - mirtazapine is actually relatively safe in CKD, while bupropion needs dose adjustment in severe impairment."
    },
    "exam_tip": "In renal impairment, think about drug and metabolite clearance. SNRIs (venlafaxine, duloxetine) need dose adjustment in CKD. SSRIs (especially sertraline) are generally safer.",
    "related_topics": ["renal-impairment", "antidepressant-prescribing", "dose-adjustment"]
  }'::jsonb
WHERE id = '5b7f60bd-9a47-4847-957f-e86ad635a6d9';

-- Question 19: Olanzapine metabolic effects
UPDATE questions SET
  is_trial_featured = TRUE,
  trial_display_order = 19,
  explanation_structured = '{
    "summary": "Olanzapine has the highest risk of metabolic side effects among commonly used antipsychotics, including substantial weight gain, diabetes, and dyslipidemia, requiring regular metabolic monitoring.",
    "key_points": [
      "Average weight gain with olanzapine is 4-5 kg in the first year",
      "Risk of diabetes is 2-3 times higher than with other antipsychotics",
      "Mechanism involves histamine H1 blockade, 5-HT2C antagonism, and effects on insulin signaling",
      "Clozapine has similar metabolic risk but additional hematological concerns"
    ],
    "clinical_pearl": "Before starting olanzapine, check baseline weight, BMI, fasting glucose, and lipid profile. Monitor these at 3 months, then annually. Consider switching if significant metabolic deterioration occurs.",
    "why_wrong": {
      "A": "Aripiprazole has the lowest metabolic risk among antipsychotics due to its partial agonist mechanism.",
      "B": "Haloperidol, a first-generation antipsychotic, has low metabolic risk but high risk of extrapyramidal side effects.",
      "D": "Lurasidone has a favorable metabolic profile with minimal weight gain and low diabetes risk.",
      "E": "Chlorpromazine has moderate metabolic risk, less than olanzapine or clozapine."
    },
    "exam_tip": "Metabolic risk ranking: Clozapine = Olanzapine > Quetiapine > Risperidone > Haloperidol > Aripiprazole. Lurasidone and ziprasidone are also metabolically favorable.",
    "related_topics": ["antipsychotic-side-effects", "metabolic-monitoring", "schizophrenia-treatment"]
  }'::jsonb
WHERE id = '41eab6eb-7b61-4651-a3b8-b56c90223486';

-- Question 20: Acute agitation management
UPDATE questions SET
  is_trial_featured = TRUE,
  trial_display_order = 20,
  explanation_structured = '{
    "summary": "Lorazepam is appropriate for immediate management of acute agitation in psychosis because it has rapid onset of action (within minutes if given IM) and effective sedating properties without worsening psychotic symptoms.",
    "key_points": [
      "Benzodiazepines provide rapid tranquillization within 15-30 minutes (IM)",
      "Lorazepam is preferred due to reliable IM absorption unlike diazepam",
      "Antipsychotics (haloperidol, olanzapine) may also be used for rapid tranquillization",
      "De-escalation and oral medication should always be tried first when safe"
    ],
    "clinical_pearl": "In acute behavioral emergencies, the NICE rapid tranquillization pathway recommends oral medication first, then IM lorazepam or haloperidol. Always have flumazenil available when using benzodiazepines.",
    "why_wrong": {
      "A": "Lithium has a slow onset of action (days to weeks) and is used for long-term mood stabilization, not acute agitation.",
      "C": "Fluoxetine is an SSRI for depression and anxiety - it takes weeks to work and has no role in acute agitation.",
      "D": "Risperidone is useful for long-term schizophrenia management but oral risperidone does not provide the immediate effect needed for acute agitation.",
      "E": "Valproate is a mood stabilizer for bipolar disorder with slow onset - inappropriate for acute agitation management."
    },
    "exam_tip": "For rapid tranquillization: Lorazepam (benzodiazepine) or haloperidol/olanzapine (antipsychotic) are the main options. Lorazepam is often first choice as it is less likely to cause acute dystonia than antipsychotics.",
    "related_topics": ["rapid-tranquillization", "psychiatric-emergencies", "benzodiazepines"]
  }'::jsonb
WHERE id = 'd6f089c7-20ab-4663-af24-5dc000df464f';

-- Summary
SELECT
  COUNT(*) as total_enhanced,
  COUNT(*) FILTER (WHERE is_trial_featured = TRUE) as trial_featured
FROM questions
WHERE explanation_structured IS NOT NULL;
